### ISSUE TITLE
So is it $HOME/.ssh, or ./sshkeys?

### ISSUE THREAD

**Issue by jahio** [cloudfoundry-community/aws-nat-bastion-bosh-cf#17]
Stumbled upon [this](https://github.com/cloudfoundry-community/aws-nat-bastion-bosh-cf/blob/master/config/aws/bosh.yml#L132) in the code while looking for something else.

``` yaml
# config/aws/bosh.yml+132
  ssh_tunnel:
    host: ${network}.1.6
    port: 22
    user: vcap
    private_key: ~/.ssh/bosh.pem
```

If we have ./sshkeys, and tell users to put their private key there, why are we referencing the user's $HOME/.ssh for the bosh.pem key?

Either:
a) This is a bug or an oversight that...somehow...we haven't stepped on this landmine, or;
b) It's intentional for some good reason _and it needs to be documented_ that **you put the key in TWO places, not just one.**
