### ISSUE TITLE
[Bug] cf-tiny.yml on bastion host has invalid syntax

### ISSUE THREAD

**Issue by jahio** [cloudfoundry-community/aws-nat-bastion-bosh-cf#23]
After the bastion host and bosh goodness are all finished, you can ssh into the bastion host and run `bosh status` to get detailed information, showing that the target for `bosh` is indeed a valid director. _However_, you still need to `bosh deployment deployments/cf-tiny.yml` to tell bosh what it's
upcoming deployment is going to be.

**When you try to parse `cf-tiny.yml`, it breaks.**

```
[centos@ip-10-10-0-95 ~]$ bosh deployment deployments/cf-tiny.yml
Incorrect YAML structure in '/home/centos/deployments/cf-tiny.yml': (<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 88 column 39
```

Here's a sample of that area in question as it exists on the bastion host:

``` yaml
jobs:
- name: messaging-z1 # "backbone"
  instances: 1
  resource_pool: small_z1
  templates:
  - { name: consul_agent, release: cf }
  - { name: etcd, release: cf }
  - { name: etcd_metrics_server, release: cf }
  - { name: nats, release: cf }
  - { name: nats_stream_forwarder, release: cf }
  - { name: doppler, release: cf }
  - { name: syslog_drain_binder, release: cf }
  - { name: metron_agent, release: cf }
  persistent_disk: 1024
  networks:
    - { name: cf_private, static_ips: [${network}.04.103]}
  properties:
    etcd_metrics_server:
      nats:
        machines: [${network}.04.103]
        password: nats
        username: natspass
```

The specific offending line is:

``` yaml
    - { name: cf_private, static_ips: [${network}.04.103]}
```

@krutten - I could have swore you fixed this already in an upstream project somewhere. I know you fixed one YAML issue that was essentially a typo, moving something to the next line down and it was fixed, but for some reason I can't seem to find any trace of it now, anywhere! Essentially this is just a YAML syntax issue, but it has to get fixed before bosh can even parse `cf-tiny.yml`, let alone do something useful with it.
